version: '3.8'

services:
  backend:
    build: .
    container_name: pipeline-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: pipeline-db
    environment:
      POSTGRES_DB: ml_social_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: super
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
